### ISSUE TITLE
Chapter Approaches spelling error

### ISSUE THREAD

**Issue by szawel** [openframeworks/ofBook#195]
Chapter Approaches/Function based movement/Sine and Cosine
in Simple examples it's

``` cpp
void ofApp::draw(){
    float xPos = ofMap(sin(ofGetElpasedTimef()), -1, 1, 0, ofGetWidth());
    ofRect(xPos, ofGetHeight()/2, 10,10);
}
```

and i think it's supposed to be 

``` cpp
void ofApp::draw(){
    float xPos = ofMap(sin(ofGetElapsedTimef()), -1, 1, 0, ofGetWidth());
    ofRect(xPos, ofGetHeight()/2, 10,10);
}

```

ofGetElpasedTimef() needs to by change to ofGetElapsedTimef()

**Comment by wongjustin99** [comment]
I hit this today, frustrating experience when I come to an issue over a year old.

**Comment by ofZach** [comment]
@szawel thanks for the correction!

@wongjustin99 sorry I just noticed the issue.  keep in mind that this is community driven project which we all did for free and because we want to help people -- it's not a professional book so sometimes we'll have some slip ups.  I didn't notice this issue but appreciate you bringing it to my attention.

**Comment by ofZach** [comment]
(also another challenge with editing this book is that there are many authors, it can sometimes be hard to know whose issue belongs to whom, etc so things slip by.... at any rate, this was a simple change !!  sorry about the error ! )

**Comment by wongjustin99** [comment]
Thanks for the super fast response! I'll try and pitch a hand in whenever I come across any more typos.

**Comment by ofZach** [comment]
thanks!!
