### ISSUE TITLE
error in demo code: balls.clear(); should read myBall.clear();

### ISSUE THREAD

**Issue by tremblap** [openframeworks/ofBook#217]
balls.clear(); 
should read 
myBall.clear();

**Comment by tremblap** [comment]
Sorry for the lack of precision: it is in the section "Making and delete as you wish - using vectors" of the chapter "Ooops! = Object Oriented Programming + Classes"

**Comment by mikewesthad** [comment]
@tremblap thanks for pointing this out! Since it's a small typo, I'm going to go ahead and make it without waiting for the author to jump in.

By the way - you can propose changes yourself if you encounter any more typos. If you open up the `.md` file for the chapter in the browser and hit the pencil icon, GitHub will allow you to propose changes without having to go through the extended fork & pull request process:

![image](https://cloud.githubusercontent.com/assets/1131802/16568658/780ec970-41f2-11e6-947c-266113609285.png)
