### ISSUE TITLE
Problem in compiling createWebBook.py

### ISSUE THREAD

**Issue by AnasGhrab** [openframeworks/ofBook#235]
```
compiling ../static/style/style.scss
Traceback (most recent call last):
  File "createWebBook.py", line 146, in <module>
    compiledCss = sass.compile(filename=staticScssFile)
AttributeError: module 'sass' has no attribute 'compile'
```

Any help ?

**Comment by mikewesthad** [comment]
@AnasGhrab do you have [libsass](https://github.com/dahlia/libsass-python) installed? That's one of the [dependencies](https://github.com/openframeworks/ofBook#building-the-book) for building the book

**Comment by mikewesthad** [comment]
I think the issue might have been having the "sass" python package installed instead of the "libsass" package (or having an out-of-date libsass package). To help avoid issues like this, I added a `requirements.txt` file to automate the installation of necessary python packages and updated installation instructions.
