### ISSUE TITLE
Animation chapter comments

### ISSUE THREAD

**Issue by kaylalewis** [openframeworks/ofBook#47]
Zach,

I went through your chapter thus far and made some minor grammatical/spelling changes, which I didn’t indicate in comments because they were so small. The chapter is coming along nicely, with a good balance of technical elements of animation and relatable examples.

Animation is tough because it gets into physics with all of the time based movement and acceleration, etc. You covered these physics lessons well. I think they’re necessary to the chapter if it’s an all-encompassing course on animation, which it seems like you’re interested in covering. Maybe throwing a few further-reading physics references into the chapter would be useful for those interested.   

As you’re progressing, I’d encourage you to consider mentioning push/pop matrix and ofTranslate. This method of animating seems more accessible for beginners, where sin and cos is a little harder to wrap your head around. I’d definitely keep the sin and cos elements, but covering push/pop matrix and ofTranslate earlier on seems relevant to this chapter, especially because they’re oF specific commands, and go along with the idea of this book being about openFrameworks. 

You used ‘OF’ and not ‘oF,’ which I left, but I thought the consensus was to use oF? It’s just really important that we choose one to stick with. 

This is picky but also important as you're adding to the chapter. I made it so there was only one space in between a period and the letter of the next sentence. I think this should be uniform throughout the entire book, too. It will cut down pages, and it’s more standard than two spaces.

Another technical comment would be choosing between em dashes or parentheses: 
–words– or (words).

…I may bring these grammatical concerns into another note because they apply to the entire book. 

Again, great analogies throughout. The best ones tied this digital way of animating to old forms of animation. These comparisons bring the artist’s role back into animating in oF, because sometimes this form of animation feels dominated by the computer and less hands on than years ago when animation was much more manual.

I look forward to seeing this chapter finished! Animation is a really important topic to cover.

**Comment by roymacdonald** [comment]
Hey @ofZach I just read the animations chapters. The only comment I would make is that in the part where you explain trigonometry you use an image that is almost the same as the maths/trigonometryExample. I think it is a good idea to rely on the OF included examples in the book as much as it is possible. Also, you mention briefly the Lissajous figures. The example maths/trigonometricMotionExample is essentially a lissajous figures generator with several oscilators.
I just remember this two because I made them :) but I'm sure there must be other cases to in which the already included examples usefuly depict something being treated in the ofBook.
BTW, Lissajous is written in your chapter Lisajous and Lissajous. I think the latter is the correct.
These are my 2 cents for now.
All the best!

**Comment by tpltnt** [comment]
Does this issue still need attention, given that it is over a year old and this moved on? If not this issue should be closed.

**Comment by tpltnt** [comment]
I am closing this issue because no one spoke up to keep it open and there is an updating pull request (#149) pending.
