### ISSUE TITLE
OOPS chapter has a memory leak?

### ISSUE THREAD

**Issue by ofZach** [openframeworks/ofBook#81]
ping @ruxrux -- I'm pretty sure there's a memory leak here :)   you use new but no delete....

	for (int i =0; i < myBall.size(); i++) {
	    float distance = ofDist(x,y, myBall[i]->x, myBall[i]->y); // a method OF give us to check the distance between two coordinates

	    if (distance < myBall[i]->dim) {
	        myBall.erase(myBall.begin()+i); // we need to use an iterator/ reference to the vector position we want to delete
	    }
	}

I generally don't think it's such a good idea to use non default constructors and pointers -- will you mind if I simplify the code / chapter a bit this week?   I think pointers / non default constructors is helpful, but I would guess this chapter can be written without the word new in it...   

I'm starting to read the book more linearly now and seeing things that seem maybe unfriendly for a beginner audience.

**Comment by arturoc** [comment]
didn't saw this before but i just answered a similar question on the forum regarding this chapter:

http://forum.openframeworks.cc/t/of-oops-tutorial/16882/6

reviewing the chapter afterwards probably it shouldn't use pointers at all since it's kind of a big topic and it's even not very good practice for something like a particle system to have particles as pointers scattered in memory.

also the polymorphism part has a bug, the draw method should be marked as virtual to act differently in the derived class when called through the vector. again it's also kind of a complicated topic and perhaps the chapter should focus more in the class syntax, how to create objects, how to do it in the different IDEs...

**Comment by ofZach** [comment]
I was just about to post pretty much the same thing :)   I think this chapter and the tutorial are a bit out of date wrt best practices.   I think we generally (and rightly) have encouraged folks to stay away from pointers (through things like default constructors) and I think it's not a good topic for beginners.  I also think it's useful to introduce ofRemove here if possible.

**Comment by ruxrux** [comment]
hey guys,

so sorry but I somehow missed this msgs.
I'll give the ooops chapter a much needed revision and cuts this week!
thanks for the feedback

.r

**Comment by tpltnt** [comment]
@ruxrux did you revise the chapter? If so this issue should be closed.
